apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: norge360-web-production

resources:
  - namespace.yaml
  - services.yaml
  - deployments.yaml
  - horizontalpodautoscalers.yaml
  - poddisruptionbudgets.yaml
  - networkpolicies.yaml
  - ingress.yaml
